name: tv-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # stack numerico compatibile con TF 2.17 (numpy 1.x)
  - numpy=1.26
  - scipy=1.11
  - pandas=2.2
  - matplotlib=3.10
  - scikit-learn>=1.3,<1.6
  # dipendenze native utili per audio/video
  - ffmpeg
  - libsndfile
  - soxr
  # OpenCV compatibile con NumPy 1.x
  - opencv=4.10
  - pip
  - pip:
      - altair~=5.5.0
      - av~=14.1.0
      - coloraide~=4.2.1
      - faster-whisper~=1.1.1
      - ffmpeg-python~=0.2.0
      - ipython~=8.32.0
      - kaleido~=0.2.1
      - librosa~=0.10.2.post1
      - nltk~=3.9.1
      - pillow~=10.4.0
      - plotly~=6.0.0
      - pydub~=0.25.1
      - pylette~=4.0.1
      - regex~=2024.11.6
      - scenedetect~=0.6.5.2
      - stanza~=1.10.1
      - tempocnn==0.0.8
      - tensorflow==2.17.0
      - tf-keras~=2.17.0
      - tensorflow-hub~=0.16.1
      - vl-convert-python~=1.8.0
      - webcolors~=24.11.1
